---
title: "Advancing public health and data science using INLA - Day 2"
author: "Janet van Niekerk (janet.vanNiekerk@kaust.edu.sa)"
output: html_document
date: "May 2024"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/vanniej/Documents/GitHub/INLA-CDC_2023")



library("INLA")
library("DiagrammeR")
library("car")
library("ggpubr")
library("spdep")
library("RColorBrewer")
library("spatstat")
library("rgdal")
library("sp")
library("maptools")
library("latticeExtra")
library("gridExtra")
library("gstat")
library("raster")
library("ggplot2")
library("ggfortify")
library("survival")
library("joineR")
#library("bayesSurv")
library("BayesSurvival")
library("icenReg")
library("nloptr")
library("faraway")
library("lme4")
library("boot")
library("rnaturalearth")
library("leaflet")
```

## Spatial models for areal data

Intro to lattice and irregular lattice

## Example 1 - Besag and Besagproper models
```{r eval=FALSE, echo = TRUE}
inla.doc("besag")
```

## Example 2 - BYM and BYM2 models
```{r eval=FALSE, echo = TRUE}
inla.doc("bym")
```

## Example 3 - Flexible Besag models (nonstationary Besag)
```{r code esmail}


#######################-------------------#######################
#------------------------Functions-------------------------------
#######################-------------------#######################

'inla.rgeneric.fbesag.model' <- function(
    cmd = c("graph", "Q", "mu", "initial", "log.norm.const",
            "log.prior", "quit"),
    theta = NULL) {
  
  sbesag <- function(R, prec, id_p, scaled_cnst, npart){
    
    get_ij <- function(g){
      
      ii <- c(); jj <- c()
      for(i in 1:g$n){
        ii <- c(ii,rep(i,g$nnbs[i]), i)
        jj <- c(jj,g$nbs[[i]], i)
      }
      return(list(i=ii,j=jj))
    }
    
    g <- inla.read.graph(R)
    
    x_scaled = c()
    for(i in 1:g$n){
      tmp <- -0.5*prec[c(id_p[g$nbs[[i]]])]
      mas_prec <- prec[id_p[i]]
      x_scaled <- c(x_scaled, tmp - 0.5*mas_prec, -sum(tmp) + 0.5*g$nnbs[i]*mas_prec + 1e-5)
    }
    r <- get_ij(g)
    return(sparseMatrix(i = r$i, j = r$j, x = scaled_cnst*x_scaled))
  }
  
  npart <- length(unique(id_p))
  dim_theta <- npart
  
  interpret.theta <- function() {
    res <- list()
    for(i in 1:dim_theta){
      res[[i]] = exp(theta[i])
    }
    return(res)
  }
  
  graph <- function(){
    require(Matrix)
    return(Matrix(W,sparse=TRUE))
  }
  
  Q <- function() {
    res <- interpret.theta()
    prec = c()
    for(i in 1:dim_theta){
      prec = c(prec, res[[i]])
    }
    
    myR <- sbesag(W, prec, id_p, scaled_cnst=scaled_cnst, npart)
    return(inla.as.sparse(myR))
  }
  
  mu <- function(){return(numeric(0))}
  
  log.norm.const <- function() {
    return (numeric(0))
  }
  
  log.prior <- function() {
    
    #p1 = 1; p2 = 1e-5 
    p1 = 0.5; p2 = 0.01
    
    lam <- - log(p2)/p1
    res <- interpret.theta()
    prec = c()
    for(i in 1:dim_theta){
      prec = c(prec, res[[i]])
    }
    
    theta_p = log(prec)
    sigm2 <- sd_sim^2
    
    mean_theta <- mean(theta_p)
    P = npart
    e = eigen(diag(P) - (1/P)*matrix(1,P,P))
    D = diag(c(1.0/e$values[1:(P-1)]))
    inv_tilda_Sigma = (1/sigm2)*e$vectors[,1:(P-1)]%*%D%*%t(e$vectors[,1:(P-1)])
    
    res1 <- log(lam) - (lam)*exp(-0.5*mean_theta) -0.5*mean_theta
    res2 <- -0.5*(theta_p-mean_theta)%*%inv_tilda_Sigma%*%(theta_p-mean_theta)
    res <- drop(res1) + drop(res2) 
    return(res)
    
    
  }
  
  initial <- function() {
    #return(initial_theta)
    return(rep(4,npart))
  }
  
  quit <- function() {
    return(invisible())
  }
  
  res <- do.call(match.arg(cmd), args = list())
  return(res)
}

#######################-------------------#######################
#-------------------------Models--------------------------------
#######################-------------------#######################

load("Data/brazil.RData")

Six_terrestrial_biomes = TRUE

constr.inter <- list(A = matrix(1,1,dim(graph)[1]), e = rep(0, 1))
scaled_graph = as.matrix(INLA:::inla.scale.model(graph,constr.inter))
scaled_cnst = scaled_graph[1,1]/graph[1,1]

id_regions <- c()
if(Six_terrestrial_biomes){
  id_regions <- data$S4
  id_regions[which(id_regions==3)] = 2
  id_regions[which(id_regions==4)] = 3
  id_regions[which(id_regions==5)] = 4
  id_regions[which(id_regions==6)] = 5
}else{
  id_regions <- data$S3
}

precision.prior <- list(prec = list(prior = "pc.prec", param = c(0.5, 0.01)))
fbesag.model <- inla.rgeneric.define(inla.rgeneric.fbesag.model, W = graph, id_p = id_regions ,scaled_cnst = scaled_cnst, sd_sim = 0.15)

data$c_S1 <- data$S1
data$c_T1 <- data$T1

config = FALSE
baseformula <- Y ~ 1 + f(S1,model="generic0", Cmatrix= scaled_graph, constr= TRUE, rankdef = 1,hyper = precision.prior) +
                       f(T1, model = "rw1", constr = TRUE,  scale.model = TRUE, hyper =  list(prec = list(prior = "pc.prec", param = c(0.5, 0.01)))) #+
                     
formula     <- Y ~ 1 + f(S1, model = fbesag.model, constr= TRUE, rankdef=1) + 
                       f(T1, model = "rw1", constr = TRUE, scale.model = TRUE, hyper = precision.prior) 

model_naive <- inla(formula = baseformula, data = data, family = "poisson", offset = log(E),
                    control.inla = list(strategy = 'gaussian', int.strategy = "eb"), 
                    control.compute = list(dic = TRUE, config = config, 
                                           cpo = TRUE, return.marginals = FALSE, control.gcpo = list(enable = TRUE,num.level.sets = 2)),
                    control.fixed = list(correlation.matrix = TRUE, 
                                         prec.intercept = 1, prec = 1),
                    control.predictor = list(link = 1, compute = TRUE), 
                    verbose = TRUE)

model_fbesag <- inla(formula = formula, data = data, family = "poisson", offset = log(E),
                     control.inla = list(strategy = 'gaussian', int.strategy = "eb"), 
                     control.compute = list(dic = TRUE, config = config, 
                                            cpo = TRUE, return.marginals = FALSE, control.gcpo = list(enable = TRUE,num.level.sets = 2)),
                     control.fixed = list(correlation.matrix = TRUE, 
                                          prec.intercept = 1, prec = 1),
                     control.predictor = list(link = 1, compute = TRUE), 
                     verbose = TRUE)

#######################-------------------#######################
#-------------------------Results--------------------------------
#######################-------------------#######################

results <- data.frame(
  Row = c("stationary", "non-stationary", "Better?"),
  DIC = c(0, 0, 0),
  CPO = c(0, 0, 0),
  GCPO = c(0, 0, 0),
  logML = c(0, 0, 0),
  MAE = c(0, 0, 0)
)

#DIC
round(model_fbesag$dic$dic,0) < round(model_naive$dic$dic,0)
round(model_fbesag$dic$dic,0) - round(model_naive$dic$dic,0)

cat(round(model_fbesag$dic$dic,0), " and ", round(model_naive$dic$dic,0))
results$DIC[1] <- round(model_naive$dic$dic,0)
results$DIC[2] <- round(model_fbesag$dic$dic,0)
results$DIC[3] <- round(model_fbesag$dic$dic,0) < round(model_naive$dic$dic,0)

#logML
model_fbesag$mlik[1] > model_naive$mlik[1]
model_fbesag$mlik[1] - model_naive$mlik[1]
cat(model_fbesag$mlik[1], " and ", model_naive$mlik[1])
results$logML[1] <- model_naive$mlik[1]
results$logML[2] <- model_fbesag$mlik[1]
results$logML[3] <- model_fbesag$mlik[1] > model_naive$mlik[1]

#gcpo
-mean(log(model_fbesag$gcpo$gcpo[model_naive$gcpo$gcpo>0])) < -mean(log(model_naive$gcpo$gcpo[model_naive$gcpo$gcpo>0])) 
cat(-mean(log(model_fbesag$gcpo$gcpo[model_naive$gcpo$gcpo>0])), " and ", -mean(log(model_naive$gcpo$gcpo[model_naive$gcpo$gcpo>0])) )
-mean(log(model_fbesag$cpo$cpo[model_naive$cpo$cpo>0])) < -mean(log(model_naive$cpo$cpo[model_naive$cpo$cpo>0])) 
results$GCPO[1] <- -mean(log(model_naive$gcpo$gcpo[model_naive$gcpo$gcpo>0])) 
results$GCPO[2] <- -mean(log(model_fbesag$gcpo$gcpo[model_naive$gcpo$gcpo>0]))
results$GCPO[3] <- -mean(log(model_fbesag$gcpo$gcpo[model_naive$gcpo$gcpo>0])) < -mean(log(model_naive$gcpo$gcpo[model_naive$gcpo$gcpo>0])) 

results$CPO[1] <- -mean(log(model_naive$cpo$cpo[model_naive$cpo$cpo>0])) 
results$CPO[2] <- -mean(log(model_fbesag$cpo$cpo[model_naive$cpo$cpo>0]))
results$CPO[3] <- -mean(log(model_fbesag$cpo$cpo[model_naive$cpo$cpo>0])) < -mean(log(model_naive$cpo$cpo[model_naive$cpo$cpo>0])) 

#MAE
data$fit_naive <- model_naive$summary.fitted.values$`0.5quant` 
data$fit_sbesag.model <- model_fbesag$summary.fitted.values$`0.5quant`
hydroGOF::mae(data$fit_naive, data$Y, na.rm = TRUE)
hydroGOF::mae(data$fit_sbesag.model, data$Y, na.rm = TRUE)

sum_mae_sbesag <- 0
sum_mae_naive <- 0

for(i in 1:5){
  sum_mae_naive <- sum_mae_naive + hydroGOF::mae(data$fit_naive[which(id_regions==i)], data$Y[which(id_regions==i)], na.rm = TRUE)
  sum_mae_sbesag <- sum_mae_sbesag + hydroGOF::mae(data$fit_sbesag.model[which(id_regions==i)], data$Y[which(id_regions==i)], na.rm = TRUE)
}
results$MAE[1] <- sum_mae_naive
results$MAE[2] <- sum_mae_sbesag
results$MAE[3] <- sum_mae_naive > sum_mae_sbesag

model_naive$internal.summary.hyperpar$mean
model_fbesag$internal.summary.hyperpar$mean

ch <- id_regions[1:558]
means <- numeric(5)
for(i in 1:5){
  means[i] <- mean(abs(model_fbesag$summary.random$S1$mean[ch==i] - model_naive$summary.random$S1$mean[ch==i]))
}

sum(model_fbesag$summary.random$S1$mean)
sum(model_naive$summary.random$S1$mean)
mean(abs(model_fbesag$summary.random$S1$mean - model_naive$summary.random$S1$mean))
f1_mean <- model_naive$internal.summary.hyperpar$mean[1]
f2_mean <- model_fbesag$internal.summary.hyperpar$mean[1:5]

f1_sd <- model_naive$internal.summary.hyperpar$sd[1]
f2_sd <- model_fbesag$internal.summary.hyperpar$sd[1:5]

#######################-------------------#######################
#--------------------- Print Results-----------------------------
#######################-------------------#######################

print(means)
print(mean(f1_mean) - mean(f2_mean))
print(mean(f1_sd) - mean(f2_sd))
print(results)
f1_mean - f2_mean
f1_sd - f2_sd





#######################-------------------#######################
#------------------------- Partitions ---------------------------
#######################-------------------#######################

library(viridis)

neigh_graphs <- poly2nb(as(map_df$geometry, "Spatial"), queen = FALSE)
values <- numeric(558)
values <- as.numeric(data$S3[1:558])

# Define custom color palette
custom_palette <- c("#f7776d", "#ffc000", "#2b8ab1", "#bbcf33", "#e76cf2")#, "#03be7d")

# Convert values to factor
values <- factor(values, levels = unique(values))

gplot <- ggplot(map_df) +
  geom_sf(aes(fill = values), lwd = 0) +
  labs(fill = "") +
  theme_void() +
  scale_fill_manual(
    values = custom_palette,
    breaks = unique(values),
    labels = c("North", "Northeast", "Southeast", "South", "Central-West")
  )

if(Six_terrestrial_biomes){
  ggsave(gplot, filename = "figs/Six_terrestrial_biomes/six_partitions.pdf", height = 4, width = 5)
}else{
  ggsave(gplot, filename = "figs/administrative_regions/five_partitions.pdf", height = 4, width = 5)
  
}


#######################-------------------#######################
#------------------------- Plots --------------------------------
#######################-------------------#######################

neigh_graphs = poly2nb(as(map_df$geometry, "Spatial"), queen = FALSE)
values <- numeric(558)
diff_m1 <- c(model_fbesag$internal.summary.hyperpar$mean[1:5]) - c(model_naive$internal.summary.hyperpar$mean[1])
for(i in 1:558) values[i] <- mean(diff_m1[id_regions[neigh_graphs[[i]]]])

gplot <- ggplot(map_df) +
  geom_sf(aes(fill = values), lwd = 0) +
  scale_fill_gradient_tableau("Blue-Teal") +
  labs(fill = "difference") +
  theme_void()  #+ scale_fill_discrete(type = "viridis", name = "", labels = c("Caatinga", "Cerrado", "Pantanal", "Pampas", "Amazon", "Atlantic Rainforest"))

if(Six_terrestrial_biomes){
  ggsave(gplot, filename = "figs/Six_terrestrial_biomes/diff_means_6_partitions.pdf", height = 4, width = 5)
}else{
  ggsave(gplot, filename = "figs/administrative_regions/diff_means_5_partitions.pdf", height = 4, width = 5)
}


neigh_graphs = poly2nb(as(map_df$geometry, "Spatial"), queen = FALSE)
values <- numeric(558)
diff_m1 <- c(model_fbesag$internal.summary.hyperpar$sd[1:5]) - c(model_naive$internal.summary.hyperpar$sd[1])
for(i in 1:558) values[i] <- mean(diff_m1[id_regions[neigh_graphs[[i]]]])

gplot <- ggplot(map_df) +
  geom_sf(aes(fill = values), lwd = 0) +
  scale_fill_gradient_tableau("Blue-Teal") +
  labs(fill = "spatial variability") +
  theme_void()  #+ scale_fill_discrete(type = "viridis", name = "", labels = c("Caatinga", "Cerrado", "Pantanal", "Pampas", "Amazon", "Atlantic Rainforest"))

if(Six_terrestrial_biomes){
  ggsave(gplot, filename = "figs/Six_terrestrial_biomes/diff_sds_6_partitions.pdf", height = 4, width = 5)
}else{
  ggsave(gplot, filename = "figs/administrative_regions/diff_sds_5_partitions.pdf", height = 4, width = 5)
}

values <- numeric(558)
diff_m1 <- model_fbesag$internal.summary.hyperpar$mean[1:5]
for(i in 1:558) values[i] <- mean(diff_m1[id_regions[neigh_graphs[[i]]]])

gplot <- ggplot(map_df) +
  geom_sf(aes(fill = values), lwd = 0) +
  scale_fill_gradient_tableau("Blue-Teal") +
  labs(fill = "spatial effect") +
  theme_void()  

if(Six_terrestrial_biomes){
  ggsave(gplot, filename = "figs/Six_terrestrial_biomes/means_6_partitions.pdf", height = 4, width = 5)
}else{
  ggsave(gplot, filename = "figs/administrative_regions/means_5_partitions.pdf", height = 4, width = 5)
}

  
##--> on time:
# time_graph <- as.matrix(INLA:::inla.rw(length(unique(data$T1)), order = 1, scale = FALSE))
# constr.inter <- list(A = matrix(1,1,dim(time_graph)[1]), e = rep(0, 1))
# scaled_graph = as.matrix(inla.scale.model(time_graph,constr.inter))
# scaled_cnst = scaled_graph[1,1]/graph[1,1]
# fbesag.time.model <- inla.rgeneric.define(inla.rgeneric.fbesag.model, W = time_graph, id_p = data$T1 ,scaled_cnst = scaled_cnst, sd_sim = 0.15)
#f(T1, model = fbesag.time.model, constr= TRUE, rankdef=1)







```

## Example 4 - Joint disease mapping models (using Besag2 model)
```{r pre}
# read data 

merg.data <- readRDS("Data/MAP_data.RDS")


# The map 
map <- ne_countries(returnclass = "sf")
names(map)[names(map) == "iso_a3"] <- "ISO3"
names(map)[names(map) == "name"] <- "NAME"
map <- map[order(map$name_long),]
map$name_long[157] <- "Gambia"
map$name_long[131] <- "Congo"

map <- map[order(map$name_long),]

# Select only the common countries from the map

sub_map <- match(map$name_long , Common.countries)
map$cc <- sub_map
map_2 <- subset(map,map$cc!="NA" )
map_2 <- map_2[order(map_2$name_long),]

Our_index <- match(map$name_long , Common.countries)


map_2$D.E = merg.data$D.E
map_2$M.E = merg.data$M.E
map_2$M.cases = merg.data$M.cases
map_2$D.cases = merg.data$D.cases
map_2$M.pop = merg.data$M.pop
map_2$D.pop = merg.data$D.pop


library(cleangeo)
rr <- clgeo_CollectionReport(map_2)
summary(rr)
issues <- rr[rr$type == NA,]
map_2_c <- clgeo_Clean(map_2)

nb <- poly2nb(map_2_c)
nb2INLA("map.adj", nb)
g <- inla.read.graph(filename = "map.adj")



alpha = 0.2
r.m <- inla(formula = map_2$M.cases ~ 1 + offset(log(map_2$M.E)) +
              f(b1,model = "bym2", scale.model = T,
                graph = g)   ,
            family = "poisson",
            # offset = log(map_2$M.E),
            #E = map_2$M.E,
            data =  merg.data,
            control.predictor = list(compute = T),
            control.compute = list(dic = T, waic = T, cpo = T),
            control.family = list(control.link = list(model = "quantile",
                                                      quantile = alpha)),
            verbose = TRUE)



round(r.m$summary.hyperpar[,c(1,3,5,6)],3)


# the quantile for G6PD only

alpha = 0.8
r.d <- inla(formula = map_2$D.cases ~ 1 + offset(log(map_2$D.E))+
              f(b2,model = "bym2", scale.model = T,
                graph = g)  ,
            family = "poisson",
            data =  merg.data,
            control.predictor = list(compute = T),
            control.compute = list(dic = T, waic = T, cpo = T),
            control.family = list(control.link = list(model = "quantile",
                                                      quantile = alpha)),
            verbose = TRUE)



round(r.d$summary.hyperpar[,c(1,3,5,6)],3)


# The joint quantile 

b = length(merg.data$M.cases)
y1 = c(merg.data$M.cases , rep(NA,b))
y2 = c(rep(NA,b) , merg.data$D.cases)


E1 = c(merg.data$M.E,rep(NA,b))
E2 = c(rep(NA,b) , merg.data$D.E)

yy = cbind(y1,y2)
EE = cbind(E1, E2)
mu = c(rep(1, b) , rep(2,b))
b1 = c(1:b,rep(NA ,b))
b2= c(rep(NA,b),1:b)

besagproper = c(1:b , rep(NA ,b))

Besag.c = c(rep(NA , b), 1:b)

m = as.factor(mu)
d = data.frame(yy, m , besagproper , Besag.c,b1,b2)  


formula = yy ~ -1 +m + offset(log(E1))+ offset(log(E2))+
  f(besagproper, model = "besagproper", graph=g)+
  f(Besag.c, copy="besagproper", hyper = list(beta = list(fixed = FALSE)))+
  f(b1 , model = "bym2", graph=g, scale.model=TRUE)+
  f(b2, model = "bym2", graph=g, scale.model=TRUE)




alpha = 0.2
r1 <- inla(formula,
           family = c("poisson","poisson"),
           
           control.family = list(list(control.link = list(model = "quantile",quantile = alpha)),
                                 
                                 list(control.link = list(model = "quantile",
                                                          quantile = 1-alpha))), 
           # E = EE,
           data = d,
           verbose = F,
           control.compute = list(dic = T, waic = T, cpo = T),
           control.predictor = list(compute = T),
           inla.mode = "experimental")


round(r1$summary.fixed[,c(1:3,5)],3)

round(r1$summary.hyperpar[,c(1,3,5,6)],3)

r1$dic$dic
r1$waic$waic


r1a <- inla(formula,
           family = c("poisson","poisson"),
           control.family = list(list(control.link = list(model = "quantile",quantile = 0.8)),
                                 list(control.link = list(model = "quantile",
                                                          quantile = 0.3))),
           data = d,
           verbose = F,
           control.compute = list(dic = T, waic = T, cpo = T),
           control.predictor = list(compute = T),
           inla.mode = "experimental")


round(r1a$summary.fixed[,c(1:3,5)],3)

round(r1a$summary.hyperpar[,c(1,3,5,6)],3)

r1a$dic$dic
r1a$waic$waic

##Joint mean
r2 <- inla(formula,
           family = c("poisson","poisson"),
           data = d,
           verbose = F,
           control.compute = list(dic = T, waic = T, cpo = T),
           control.predictor = list(compute = T),
           inla.mode = "experimental")


round(r2$summary.fixed[,c(1:3,5)],3)

round(r2$summary.hyperpar[,c(1,3,5,6)],3)

r2$waic$waic
r2$dic$dic







# the iid EFFECT malaria

map_2$vm = (r.m$summary.random$b1$mean[1:21] * sqrt(r.m$summary.hyperpar$mode[1]) -  
             r.m$summary.random$b1$mean[22:42] * sqrt(r.m$summary.hyperpar$mode[2])) / 
  sqrt(1 - r.m$summary.hyperpar$mode[2])

map_2$um = r.m$summary.random$b1$mean[22:42] 

range(map_2$vm)


l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", 
                    domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$vm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "IID effect for Malaria",
            position = "topright")

# the iid EFFECT g6

map_2$vd2 = (r.d$summary.random$b2$mean[1:21] * sqrt(r.d$summary.hyperpar$mode[1]) -  
              r.d$summary.random$b2$mean[22:42] * sqrt(r.d$summary.hyperpar$mode[2])) / 
  sqrt(1 - r.d$summary.hyperpar$mode[2])

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$vd2), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "IID effect for G6PD",
            position = "topright")



# the spatial effect for malaria

map_2$u.m2 = r.m$summary.random$b1$mean[22:42]

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$u.m2), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "Besag effect for Malaria",
            position = "topright")

# the spatial effect for G6PD

map_2$u.d2 = r.d$summary.random$b2$mean[22:42]

range(map_2$u.d2)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$u.d2), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "Besag effect for G6PD",
            position = "topright")

mean(abs(map_2$iid))
mean(abs(map_2$u.m2))

range(map_2$iid2)
range(map_2$u.d2)





# The relative risk for malaria 

map_2$rrm = r.m$summary.fitted.values[,"mean"]/map_2$M.E
range(map_2$rrm)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()
pal <- colorNumeric(palette = "YlOrRd", 
                    domain = seq(0,6.3 , by = 0.1))
l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$rrm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(0,6.3 , by = 0.1), 
            opacity = 0.5, title = "RR",
            position = "topright")


# The realtive risk for G6PD

map_2$rrd = r.d$summary.fitted.values[,"mean"]/map_2$D.E
range(map_2$rrd)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0, 6.3, length = 9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$rrd), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0, 6.3, length = 9), 
            opacity = 0.5, title = "RR",
            position = "topright")

# The predicted cases fr Malaria 

map_2$Predicted.MM = r.m$summary.fitted.values$mean
range(map_2$Predicted.MM)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,40000, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$Predicted.MM), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,40000, length =9), 
            opacity = 0.5, title = "Predicted",
            position = "topright")


#Observed

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,40000, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$M.cases), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,40000, length =9), 
            opacity = 0.5, title = "Observed",
            position = "topright")




# The predected cases for G6PD


map_2$Predicted.DD = r.d$summary.fitted.values$mean
range(map_2$Predicted.DD)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,500 , by = 10))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$Predicted.DD), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,500 , by = 10), 
            opacity = 0.5, title = "Predicted",
            position = "topright")



#Observed

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,500, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$D.cases), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,500, length =9), 
            opacity = 0.5, title = "Observed",
            position = "topright")










# iid effect for malaria

map_2$vmq = (r1$summary.random$b1$mean[1:21] * sqrt(r1$summary.hyperpar$mode[3]) -  
             r1$summary.random$b1$mean[22:42] * sqrt(r1$summary.hyperpar$mode[4])) / 
  sqrt(1 - r1$summary.hyperpar$mode[4])

range(map_2$vmq)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$vmq), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "IID",
            position = "topright")


# iid effect for g6pd

map_2$v = (r1$summary.random$b2$mean[1:21] * sqrt(r1$summary.hyperpar$mode[5]) -  
              r1$summary.random$b2$mean[22:42] * sqrt(r1$summary.hyperpar$mode[6])) / 
              sqrt(1 - r1$summary.hyperpar$mode[6])

range(map_2$v)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$v), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "IID",
            position = "topright")








# The shared component for Malaria 

map_2$sharedqm = r1$summary.random$besagproper$mean
range(map_2$sharedqm)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-1.5,0.8 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$sharedqm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-1.5,0.8 , by = 0.1), 
            opacity = 0.5, title = "Shared effect",
            position = "bottomleft")


# The shared component for G6PD

map_2$sharedqd = r1$summary.random$Besag.c$mean
range(map_2$sharedqd)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$sharedqd), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "Shared  effect",
            position = "bottomleft")


# The spatial effect for Malaria from joint 


map_2$sjm = r1$summary.random$b1$mean[22:42]

range(map_2$sjm)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-1,0.5 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$sjm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-1,0.5 , by = 0.1), 
            opacity = 0.5, title = "Besag",
            position = "topright")



# The spatial effect for G6PD from joint 

map_2$sjg = r1$summary.random$b2$mean[22:42]

range(map_2$sjg)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$sjg), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "Besag",
            position = "topright")





# Posterior means of the total spatial effect for Malaria (quntile)


map_2$tsmq = r1$summary.random$b1$mean[22:42]+r1$summary.random$besagproper$mean

range(map_2$tsmq) 


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$tsmq), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = " Total spatial effect",
            position = "topright")




# Posterior means of the total spatial effect for g6pd (quntile)

map_2$tsgq = r1$summary.random$b2$mean[22:42]+r1$summary.random$Besag.c$mean

range(map_2$tsgq) 


l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$tsgq ), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = " Total spatial effect",
            position = "topright")


# RR for malaria from joint quantile 



map_2$rrjm = r1$summary.fitted.values[1:21, "mean"]/map_2$M.E

range(map_2$rrjm) 


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,6.3, by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$rrjm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,6.3, by = 0.1), 
            opacity = 0.5, title = "RR",
            position = "topright")

# rr from joint for d

map_2$rrjd = r1$summary.fitted.values[22:42, "mean"]/map_2$D.E

range(map_2$rrjd) 


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,6.3, by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$rrjd), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,6.3, by = 0.1), 
            opacity = 0.5, title = "RR",
            position = "topright")




# The predicted cases for m from joint




map_2$pm = r1$summary.fitted.values$mean[1:21]

range(map_2$pm) 


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,40000, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$pm), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,40000, length =9), 
            opacity = 0.5, title = "Predicted",
            position = "topright")


l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,40000, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$M.cases), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,40000, length =9), 
            opacity = 0.5, title = "Observed",
            position = "topright")


# The predicted cases for d from joint


map_2$pd = r1$summary.fitted.values$mean[22:42]
range(map_2$pd) 

# map_2$pd1 = exp(r$summary.linear.predictor$mean[22:42])
# range(map_2$pd1)

library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,500, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$pd), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,500, length =9), 
            opacity = 0.5, title = "Predicted",
            position = "topright")

#Observed

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain =seq(0,500, length =9))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$D.cases), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~ seq(0,500, length =9), 
            opacity = 0.5, title = "Observed",
            position = "topright")


# bym malaria from joint 

map_2$bymmq = r1$summary.random$b1$mean[1:21]

range(map_2$bymmq)


library(leaflet)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$bymmq), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "BYM effect for Malaria",
            position = "bottomleft")





# bym g6pd from joint 

map_2$bymgq = r1$summary.random$b2$mean[1:21]

range(map_2$bymgq)

l <- leaflet(map_2) %>% addTiles()

pal <- colorNumeric(palette = "YlOrRd", domain = seq(-5.6,2.6 , by = 0.1))


l %>% addPolygons(color = "grey", weight = 1, 
                  fillColor = ~pal(map_2$bymgq), 
                  fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~seq(-5.6,2.6 , by = 0.1), 
            opacity = 0.5, title = "BYM effect for G6PD",
            position = "topright")



```

